# Generated by Django 5.1.3 on 2024-12-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=50)),
                ('account_name', models.CharField(default='Default Account', max_length=255)),
                ('lead_provider_id', models.IntegerField()),
                ('language', models.CharField(default='en', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='organization.organizationmodel')),
            ],
            options={
                'db_table': 'account_detail',
            },
        ),
    ]
