# Generated by Django 4.2.17 on 2024-12-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='lead_provider_id',
            new_name='team_leader_id',
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='account_name',
            field=models.CharField(max_length=255),
        ),
    ]
