# Generated by Django 4.2.17 on 2025-01-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_lead_provider_id_accountmodel_team_leader_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
