# Generated by Django 5.1.3 on 2024-12-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
