# Generated by Django 4.2.17 on 2025-01-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_useraccountmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountmodel',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='useraccountmodel',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
