# Generated by Django 5.0.2 on 2025-02-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('project_assigned', 'Project Assigned'), ('message', 'Message')], max_length=50)),
                ('from_id', models.PositiveIntegerField()),
                ('from_type', models.CharField(max_length=50)),
                ('to_id', models.PositiveIntegerField()),
                ('to_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notifi',
            },
        ),
    ]
