# Generated by Django 5.0.2 on 2025-02-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notifi',
        ),
    ]
