# Generated by Django 5.0.2 on 2025-02-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notification_table',
        ),
    ]
