# Generated by Django 5.0.2 on 2025-01-29 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_accountmodel_is_active_and_more'),
        ('organization', '0002_alter_organizationmodel_id'),
        ('program', '0003_program_is_active_program_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_to', models.TextField()),
                ('assign_type', models.CharField(choices=[('user', 'User'), ('team', 'Team')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountmodel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationmodel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
    ]
