# Generated by Django 5.0.2 on 2025-01-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignedprogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedprogrammodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
