# Generated by Django 5.0.2 on 2025-01-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignedprogram', '0002_alter_assignedprogrammodel_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedprogrammodel',
            name='account',
        ),
        migrations.RemoveField(
            model_name='assignedprogrammodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='assignedprogrammodel',
            name='program',
        ),
        migrations.AddField(
            model_name='assignedprogrammodel',
            name='account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedprogrammodel',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedprogrammodel',
            name='program_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
