# Generated by Django 5.0.2 on 2025-01-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignedprogram', '0003_remove_assignedprogrammodel_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedprogrammodel',
            name='is_completed',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
