# Generated by Django 4.2.17 on 2025-01-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_rename_writtenby_program_written_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='program',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
