# Generated by Django 5.1.3 on 2025-01-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programactivity', '0002_programactivitymodel_day_programactivitymodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programactivitymodel',
            name='time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
