# Generated by Django 4.2.17 on 2025-01-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programactivity', '0002_programactivitymodel_day_programactivitymodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programactivitymodel',
            name='time',
        ),
        migrations.AlterField(
            model_name='programactivitymodel',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('survey', 'survey'), ('challenge', 'challenge'), ('interview', 'interview'), ('video', 'video'), ('podcast', 'podcast'), ('workshop', 'workshop'), ('assignment', 'assignment'), ('excercise', 'excercise'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
