# Generated by Django 4.2.17 on 2025-01-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programactivity', '0003_remove_programactivitymodel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programactivitymodel',
            name='time',
            field=models.CharField(blank=True, default='0', null=True),
        ),
    ]
