# Generated by Django 4.2.17 on 2025-01-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programactivity', '0004_programactivitymodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programactivitymodel',
            name='time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
