# Generated by Django 4.2.17 on 2025-01-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0003_program_is_active_program_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('week_no', models.IntegerField()),
                ('language', models.CharField(blank=True, choices=[('en', 'english'), ('fr', 'french'), ('nl', 'dutch'), ('hn', 'hindi')], max_length=50, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('who', models.TextField(blank=True, max_length=255, null=True)),
                ('activity_type', models.CharField(blank=True, null=True)),
                ('completion_check', models.CharField(blank=True, null=True)),
                ('show_completed', models.BooleanField(blank=True, default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('user_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('teamlead_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('coach_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('coach_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('travel_time', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('upload_possible', models.CharField(blank=True, default='no', null=True)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('activity_name', models.TextField(blank=True, max_length=255, null=True)),
                ('send_reminder', models.CharField(blank=True, default='no')),
                ('show_in_task', models.CharField(blank=True, default='no')),
                ('add_comment_option', models.CharField(blank=True, default='no')),
                ('indicate_when_completed', models.CharField(blank=True, default='no', null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('is_deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='program.program')),
            ],
            options={
                'db_table': 'week_table',
            },
        ),
    ]
