# Generated by Django 4.2.17 on 2025-01-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, choices=[('english', 'english'), ('french', 'french'), ('other', 'other'), ('hindi', 'hindi')], max_length=50, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('who', models.TextField(blank=True, max_length=255, null=True)),
                ('activity_type', models.CharField(blank=True, null=True)),
                ('completion_check', models.CharField(blank=True, null=True)),
                ('show_completed', models.BooleanField(blank=True, default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('user_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('teamlead_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('coach_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('coach_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('travel_time', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('upload_possible', models.CharField(blank=True, default='no', null=True)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('activity_name', models.TextField(blank=True, max_length=255, null=True)),
                ('send_reminder', models.CharField(blank=True, default='no')),
                ('show_in_task', models.CharField(blank=True, default='no')),
                ('add_comment_option', models.CharField(blank=True, default='no')),
                ('indicate_when_completed', models.CharField(blank=True, default='no', null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('is_deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_table',
            },
        ),
    ]
