# Generated by Django 4.2.17 on 2025-01-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'english'), ('fr', 'french'), ('nl', 'dutch'), ('hn', 'hindi')], max_length=50, null=True),
        ),
    ]
