# Generated by Django 5.1.3 on 2024-12-09 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, minimum 2 characters', regex='^[a-zA-Z\\s]{2,}$')])),
                ('team_leader_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('user_type', models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('PATIENT', 'Patient'), ('HEALTHCARE_PROVIDER', 'Healthcare Provider'), ('TEAMLEAD', 'Teamlead'), ('FRIEND', 'Friend')], default='PATIENT', error_messages={'invalid_choice': 'Please select a valid user type'}, max_length=50)),
                ('profile_picture', models.ImageField(blank=True, error_messages={'invalid': 'Please upload a valid image file', 'invalid_image': 'The uploaded file is not a valid image'}, max_length=255, null=True, upload_to='media/')),
                ('language_preference', models.CharField(blank=True, default='en', max_length=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', error_messages={'invalid_choice': 'Please select a valid status'}, max_length=50)),
                ('is_team_leader', models.BooleanField(default=False)),
                ('wly_token', models.BooleanField(default=False)),
                ('is_used_token', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.accountmodel')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
