# Generated by Django 5.1.3 on 2024-12-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please upload a valid image file', 'invalid_image': 'The uploaded file is not a valid image'}, max_length=255, null=True),
        ),
    ]
