# Generated by Django 5.1.3 on 2024-11-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(error_messages={'blank': 'Password cannot be blank', 'required': 'Password is required'}, max_length=128),
        ),
    ]
