# Generated by Django 5.1.3 on 2024-12-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_usermodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('PATIENT', 'Patient'), ('HEALTHCARE_PROVIDER', 'Healthcare Provider'), ('TEAMLEAD', 'Teamlead'), ('ADMIN', 'Admin')], default='PATIENT', error_messages={'invalid_choice': 'Please select a valid user type'}, max_length=50),
        ),
    ]
