# Generated by Django 5.1.3 on 2024-11-22 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(error_messages={'blank': 'Password cannot be blank', 'required': 'Password is required'}, max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='Password must contain letters and numbers', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$')]),
        ),
    ]
