# Generated by Django 5.1.3 on 2024-12-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='language_preference',
            field=models.CharField(blank=True, default='English', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='ACTIVE', error_messages={'invalid_choice': 'Please select a valid status'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('patient', 'patient'), ('admin', 'admin')], default='PATIENT', error_messages={'invalid_choice': 'Please select a valid user type'}, max_length=50),
        ),
    ]
