# Generated by Django 5.1.3 on 2024-12-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_usermodel_language_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='language_preference',
            field=models.CharField(blank=True, default='english', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', error_messages={'invalid_choice': 'Please select a valid status'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('patient', 'patient'), ('admin', 'admin')], default='patient', error_messages={'invalid_choice': 'Please select a valid user type'}, max_length=50),
        ),
    ]
