# Generated by Django 5.1.3 on 2024-12-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_usermodel_language_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('patient', 'patient'), ('admin', 'admin'), ('superadmin', 'superadmin')], default='patient', error_messages={'invalid_choice': 'Please select a valid user type'}, max_length=50),
        ),
    ]
