# Generated by Django 5.1.3 on 2024-11-25 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Please enter a valid email address', 'unique': 'An account with this email already exists'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='language_preference',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, minimum 2 characters', regex='^[a-zA-Z\\s]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(error_messages={'blank': 'Password cannot be blank', 'required': 'Password is required'}, max_length=128, validators=[django.core.validators.MinLengthValidator(8, 'Password must be at least 8 characters long'), django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter, one lowercase letter, one number and one special character (@$!%*?&#)', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&#])[A-Za-z\\d@$!%*?&#]{8,}$')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', error_messages={'invalid_choice': 'Please select a valid status'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='team_leader_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('PATIENT', 'Patient'), ('HEALTHCARE_PROVIDER', 'Healthcare Provider'), ('TEAMLEAD', 'Teamlead'), ('FRIEND', 'Friend')], default='PATIENT', error_messages={'invalid_choice': 'Please select a valid user type'}, max_length=50),
        ),
    ]
