# Generated by Django 5.1.3 on 2024-11-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_usermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, error_messages={'invalid': 'Please upload a valid image file', 'invalid_image': 'The uploaded file is not a valid image'}, max_length=255, null=True, upload_to='media/'),
        ),
    ]
