# Generated by Django 5.1.3 on 2024-12-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_usermodel_managers_usermodel_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
    ]
