# Generated by Django 5.1.3 on 2024-12-03 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_remove_usermodel_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(error_messages={'blank': 'Password cannot be blank', 'required': 'Password is required'}, max_length=128, validators=[django.core.validators.MinLengthValidator(8, 'Password must be at least 8 characters long'), django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter, one lowercase letter, one number and one special character (@$!%*?&#)', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&#])[A-Za-z\\d@$!%*?&#]{8,}$')]),
        ),
    ]
