# Generated by Django 5.1.3 on 2024-12-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_usermodel_groups_usermodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='account_id',
        ),
    ]
