# Generated by Django 5.1.3 on 2024-12-03 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('userapp', '0012_remove_usermodel_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.accountmodel'),
        ),
    ]
