# Generated by Django 5.1.3 on 2024-12-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_remove_usermodel_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
    ]
