# Generated by Django 4.2.17 on 2025-01-21 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('data sharing', 'Data Sharing'), ('third-party access', 'Third-party Access')], max_length=20)),
                ('consent_status', models.CharField(choices=[('given', 'Given'), ('revoked', 'Revoked')], default='given', max_length=10)),
                ('consent_date', models.DateField(auto_now_add=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_table',
            },
        ),
    ]
