# Generated by Django 4.2.17 on 2024-12-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0002_alter_activityactiontype_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityactiontype',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityactiontype',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='activityactiontype',
            table=None,
        ),
    ]
