# Generated by Django 4.2.17 on 2025-01-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0003_alter_activityactiontype_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityactiontype',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
