# Generated by Django 4.2.17 on 2025-01-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0004_alter_activityactiontype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityactiontype',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activityactiontype',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
