# Generated by Django 5.1.3 on 2025-01-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0005_alter_activityactiontype_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityactiontype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
