# Generated by Django 4.2.17 on 2024-12-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('Survey', 'Survey'), ('Challenge', 'Challenge'), ('Interview', 'Interview'), ('Video', 'Video'), ('Podcast', 'Podcast'), ('Workshop', 'Workshop'), ('Assignment', 'Assignment'), ('Exercise', 'Exercise'), ('Other', 'Other')], max_length=50)),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Other', 'Other')], max_length=50)),
                ('activity', models.CharField(max_length=255)),
                ('who', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('todo', models.TextField(blank=True, null=True)),
                ('send_reminder', models.BooleanField(default=False)),
                ('add_comment_option', models.BooleanField(default=False)),
                ('show_completed', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('user_duration', models.IntegerField(blank=True, null=True)),
                ('duration_teamlead', models.IntegerField(blank=True, null=True)),
                ('duration_coach', models.IntegerField(blank=True, null=True)),
                ('coach_type', models.CharField(blank=True, max_length=50, null=True)),
                ('travel_time', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('upload_possible', models.BooleanField(default=False)),
            ],
        ),
    ]
