# Generated by Django 4.2.17 on 2024-12-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
