# Generated by Django 4.2.17 on 2024-12-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_intervention_amount_intervention_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='todo',
            field=models.BooleanField(default=False),
        ),
    ]
