# Generated by Django 4.2.17 on 2024-12-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_intervention_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='indicate_when_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervention_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervention_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='show_in_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
