# Generated by Django 4.2.17 on 2024-12-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_intervention_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
