# Generated by Django 4.2.17 on 2024-12-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_intervention_created_at_intervention_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='price',
        ),
        migrations.AddField(
            model_name='intervention',
            name='activity_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='completion_check',
            field=models.TextField(blank=True, null=True),
        ),
    ]
