# Generated by Django 4.2.17 on 2024-12-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_remove_intervention_duration_teamlead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='intervention_type',
            field=models.CharField(blank=True, choices=[('survey', 'survey'), ('challenge', 'challenge'), ('interview', 'interview'), ('video', 'video'), ('podcast', 'podcast'), ('workshop', 'workshop'), ('assignment', 'assignment'), ('exercise', 'exercise'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('french', 'french'), ('other', 'other')], max_length=50),
        ),
    ]
