# Generated by Django 5.1.3 on 2025-01-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_alter_intervention_duration_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='coach_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='upload_possible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
