# Generated by Django 5.1.3 on 2025-01-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_alter_intervention_coach_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='user_duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
