# Generated by Django 5.1.3 on 2025-01-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_alter_intervention_user_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='duration_teamlead',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='indicate_when_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervention',
            name='travel_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
