# Generated by Django 5.1.3 on 2025-01-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_intervention_duration_teamlead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='user_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
