# Generated by Django 5.1.3 on 2025-01-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_alter_intervention_user_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='duration_coach',
            new_name='coach_duration',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='duration_teamlead',
        ),
        migrations.AddField(
            model_name='intervention',
            name='teamlead_duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='add_comment_option',
            field=models.CharField(default='no'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_type',
            field=models.CharField(blank=True, choices=[('survey', 'survey'), ('challenge', 'challenge'), ('interview', 'interview'), ('video', 'video'), ('podcast', 'podcast'), ('workshop', 'workshop'), ('assignment', 'assignment'), ('excercise', 'excercise'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='send_reminder',
            field=models.CharField(default='no'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='show_in_tasks',
            field=models.CharField(default='no'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='user_duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='who',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
