# Generated by Django 5.1.3 on 2025-01-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_rename_show_in_tasks_intervention_show_in_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='add_comment_option',
            field=models.CharField(blank=True, default='no'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'english'), ('french', 'french'), ('other', 'other'), ('hindi', 'hindi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='send_reminder',
            field=models.CharField(blank=True, default='no'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='show_in_task',
            field=models.CharField(blank=True, default='no'),
        ),
    ]
