# Generated by Django 4.2.17 on 2025-01-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_alter_intervention_add_comment_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='show_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
